name: Build & Push Frontend Planify 

on:
  push:
    branches: [Pre-Development]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/frendikapratama/frontendtodolist:${{ github.sha }}
            ghcr.io/frendikapratama/frontendtodolist:0.0.1
